#!/usr/bin/env bash
PATH=/bin:/usr/bin:/usr/sbin

#  Test the system version to determine at which index the Toolbar button 
#  should be added.
# 
if [ `defaults read /System/Library/CoreServices/SystemVersion ProductVersion | grep '^10\.5'` ]; then
  INDEX=4
else
  INDEX=3
fi

#  Use the 'Buddy to add the Toolbar button for all users of the system.
#
PLISTBUDDY="${1}/Contents/Resources/PlistBuddy"
for HOME in `ls -d /Users/[^\.]* | sed 's/^.*\/Shared//g'`; do
  ITEMS=`"$PLISTBUDDY" -c "Print ':NSToolbar Configuration SafariToolbarIdentifier:TB Item Identifiers:'" $HOME/Library/Preferences/com.apple.Safari.plist`
  if ! echo $ITEMS | grep -q FLVR -; then
    "$PLISTBUDDY" -c "Add ':NSToolbar Configuration SafariToolbarIdentifier:TB Item Identifiers:'$INDEX string FLVR" $HOME/Library/Preferences/com.apple.Safari.plist
  fi
done

exit 0;
